### ISSUE TITLE
Catch-22

### ISSUE THREAD

**Issue by joshbeard** [xaque208/puppet-pf#2]
I've noticed a few things when using this module:

* The `/dev/pf` device needs to exist before `pfctl` can be executed.
* The service `pf` provides that device, but the service can't start without `/etc/pf.conf`
* The module manages `/etc/pf.conf`, but it ultimately requires the service to be running first (if that's what we're depending on to provide `/dev/pf`).

Perhaps this module can optionally manage the `pf` service as well?

**Comment by xaque208** [comment]
Wow, apologies for the delay.  I just realized I've not been watching this repo.  I now am.

**Comment by joshbeard** [comment]
I believe this is solved by #3 and #4

**Comment by xaque208** [comment]
Oh good, thanks for checking back.
